name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ./build

    - name: Build
      run: cmake --build ./build --parallel

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: cmake --build ./build --target test
